image: node:12-alpine

pages:
  cache:
    paths:
      - node_modules/
      - .ycache
  script:
    - yarn --cache-folder ./.ycache
    - yarn run nx build frontend -c gitlabPages
  artifacts:
    paths:
      - public
  only:
    - master
    - pages
