version: "3.7"

services:
  facade:
    image: nginx:1.14-alpine
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./facade/nginx/facade.local.conf:/etc/nginx/conf.d/default.conf
    networks:
      default:
        aliases:
          - local-facade
    links:
      - "frontend"
      - "api"

  frontend:
    image: ${IMAGE}:${TAG}-frontend
    # build:
    #   context: ./
    #   dockerfile: ./apps/frontend/docker/Dockerfile
    restart: always
    ports:
      - "8082:80"
    networks:
      default:
        aliases:
          - local-frontend
    links:
      - "api"

  api:
    image: ${IMAGE}:${TAG}-api
    # build:
    #   context: ./
    #   dockerfile: ./apps/api/docker/Dockerfile
    restart: always
    ports:
      - "9222:9222"
      - "3001:3001"
    environment:
      - DATABASE_URI=mongodb://mongo:27017/netguru-test-app
      - HOSTNAME=0.0.0.0
    volumes:
      - api:/usr/src/app/data
    links:
      - "mongo"
      - "redis"

  mongo:
    image: "mongo:4.4"
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"

  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  api:
    external: true
    name: linkedout-api-vol
  mongo:
    external: true
    name: linkedout-mongo-vol
