type User {
  _id: ID!
  email: String!
  firstName: String
  lastName: String
}

type LoginOutput {
  accessToken: String!
}

type Query {
  getAll: [User!]!
}

type Mutation {
  registerUser(input: RegisterUserInput!): User!
  login(password: String!, email: String!): LoginOutput!
}

input RegisterUserInput {
  email: String!
  password: String!
  firstName: String
  lastName: String
}
