type User {
  _id: ID!
  email: String!
  firstName: String
  lastName: String
}

type LoginOutput {
  accessToken: String!
}

type Task {
  _id: ID!
  user: User!
  userId: String!
  name: String!
  completed: Boolean!
  description: String
  date: DateTime
}

"""
A date-time string at UTC, such as 2019-12-03T09:54:33Z, compliant with the date-time format.
"""
scalar DateTime

type Query {
  getMyTasks: [Task!]!
  getMyUser: User!
}

type Mutation {
  login(password: String!, email: String!): LoginOutput!
  registerUser(input: RegisterUserInput!): User!
  createMyTask(input: CreateMyTaskInput!): Task!
  updateMyTask(input: UpdateMyTaskInput!): Task!
  removeMyTask(input: RemoveMyTaskInput!): Task!
  completeMyTask(input: CompleteMyTaskInput!): Task!
}

input RegisterUserInput {
  email: String!
  password: String!
  firstName: String
  lastName: String
}

input CreateMyTaskInput {
  name: String!
  description: String = ""
  date: String
}

input UpdateMyTaskInput {
  name: String
  description: String = ""
  date: String
  _id: ID!
}

input RemoveMyTaskInput {
  _id: ID!
}

input CompleteMyTaskInput {
  _id: ID!
}
