mutation login($email: String!, $password: String!) {
  login(email: $email, password: $password) {
    accessToken
    me {
      _id
      firstName
      lastName
      email
    }
  }
}

mutation registerUser($input: RegisterUserInput!) {
  registerUser(input: $input) {
    _id
    email
    firstName
    lastName
  }
}
